# https://rust-lang.github.io/rustfmt/
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity="Crate"
imports_layout = "Mixed"
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
